jobs:
  include:
    - dist: xenial
      language: java
      jdk:
        - openjdk8
        - openjdk10
        - openjdk11
      before_script:
        - cd java
      script:
        - ./gradlew test
    - dist: xenial
      language: php
      php:
        - '7.3'
        - '7.4'
      before_script:
        - cd php
      script:
        - composer install --dev
        - composer test
