matrix:
  include:
    - dist: xenial
      language: java
      jdk:
        - openjdk8
        - openjdk10
        - openjdk11
      before_script:
        - cd java
      script:
        - ./gradlew test
